name: "Deploy Node App"
description: "Deploy node app by running index.js directly (no PM2)"

inputs:
  environment:
    description: 'Environment to deploy'
    required: true
  port:
    description: 'Port number'
    required: true

runs:
  using: composite
  steps:
    - name: Deployment message
      run: Write-Output "Deployment to ${{ inputs.environment }} on port ${{ inputs.port }} has started.."
      shell: cmd

    - name: Install dependencies
      run: npm install
      shell: cmd

    - name: Start index.js (simulated PM2)
      run: |
        Start-Process "node" -ArgumentList "index.js", "${{ inputs.port }}"
        Write-Output "Server started using node index.js on port ${{ inputs.port }}"
      shell: cmd
